import 'typings-global';
export import beautylog = require('beautylog');
export import dockersock = require('dockersock');
export let fs = require('fs-extra');
export let gulp = require('gulp');
export import lodash = require('lodash');
export let moment = require('moment');
export import path = require('path');
export import q = require('q');
export import request = require('request');
export import rxjs = require('rxjs');
export let shelljs = require('shelljs');
export import smartfile = require('smartfile');
export import smartnginx = require('smartnginx');
export import smartstring = require('smartstring');
export import taskbuffer = require('taskbuffer');
export import through2 = require('through2');
